/*
 * C header file for format conversion of integer types.
 *
 * Copyright (C) 2026 Ivan Janevski
 *
 * ivancc is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * ivancc is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * for more details.
 *
 * Under Section 7 of GPL version 3, you are granted additional
 * permissions described in the GCC Runtime Library Exception, version
 * 3.1, as published by the Free Software Foundation.
 *
 * You should have received a copy of the GNU General Public License and
 * a copy of the GCC Runtime Library Exception along with ivancc; see
 * the files LICENSE and COPYING.RUNTIME respectively.  If not, see
 * <https://www.gnu.org/licenses/>.
 */

#ifndef __INTTYPES_H__
#define __INTTYPES_H__

// Standard headers.
#include <stdint.h>

// The implementation.
#include <libc/impl/libc_inttypes.h>

// (S7.8) Format conversion of integer types
typedef _Libc_Impl_Inttypes_imaxdiv_t imaxdiv_t;

// (S7.8.1) Macros for format specifiers
#define PRId8 _LIBC_IMPL_INTTYPES_PRId8
#define PRId16 _LIBC_IMPL_INTTYPES_PRId16
#define PRId32 _LIBC_IMPL_INTTYPES_PRId32
#define PRId64 _LIBC_IMPL_INTTYPES_PRId64
#define PRIdLEAST8 _LIBC_IMPL_INTTYPES_PRIdLEAST8
#define PRIdLEAST16 _LIBC_IMPL_INTTYPES_PRIdLEAST16
#define PRIdLEAST32 _LIBC_IMPL_INTTYPES_PRIdLEAST32
#define PRIdLEAST64 _LIBC_IMPL_INTTYPES_PRIdLEAST64
#define PRIdFAST8 _LIBC_IMPL_INTTYPES_PRIdFAST8
#define PRIdFAST16 _LIBC_IMPL_INTTYPES_PRIdFAST16
#define PRIdFAST32 _LIBC_IMPL_INTTYPES_PRIdFAST32
#define PRIdFAST64 _LIBC_IMPL_INTTYPES_PRIdFAST64
#define PRIdMAX _LIBC_IMPL_INTTYPES_PRIdMAX
#define PRIdPTR _LIBC_IMPL_INTTYPES_PRIdPTR
#define PRIi8 _LIBC_IMPL_INTTYPES_PRIi8
#define PRIi16 _LIBC_IMPL_INTTYPES_PRIi16
#define PRIi32 _LIBC_IMPL_INTTYPES_PRIi32
#define PRIi64 _LIBC_IMPL_INTTYPES_PRIi64
#define PRIiLEAST8 _LIBC_IMPL_INTTYPES_PRIiLEAST8
#define PRIiLEAST16 _LIBC_IMPL_INTTYPES_PRIiLEAST16
#define PRIiLEAST32 _LIBC_IMPL_INTTYPES_PRIiLEAST32
#define PRIiLEAST64 _LIBC_IMPL_INTTYPES_PRIiLEAST64
#define PRIiFAST8 _LIBC_IMPL_INTTYPES_PRIiFAST8
#define PRIiFAST16 _LIBC_IMPL_INTTYPES_PRIiFAST16
#define PRIiFAST32 _LIBC_IMPL_INTTYPES_PRIiFAST32
#define PRIiFAST64 _LIBC_IMPL_INTTYPES_PRIiFAST64
#define PRIiMAX _LIBC_IMPL_INTTYPES_PRIiMAX
#define PRIiPTR _LIBC_IMPL_INTTYPES_PRIiPTR
#define PRIo8 _LIBC_IMPL_INTTYPES_PRIo8
#define PRIo16 _LIBC_IMPL_INTTYPES_PRIo16
#define PRIo32 _LIBC_IMPL_INTTYPES_PRIo32
#define PRIo64 _LIBC_IMPL_INTTYPES_PRIo64
#define PRIoLEAST8 _LIBC_IMPL_INTTYPES_PRIoLEAST8
#define PRIoLEAST16 _LIBC_IMPL_INTTYPES_PRIoLEAST16
#define PRIoLEAST32 _LIBC_IMPL_INTTYPES_PRIoLEAST32
#define PRIoLEAST64 _LIBC_IMPL_INTTYPES_PRIoLEAST64
#define PRIoFAST8 _LIBC_IMPL_INTTYPES_PRIoFAST8
#define PRIoFAST16 _LIBC_IMPL_INTTYPES_PRIoFAST16
#define PRIoFAST32 _LIBC_IMPL_INTTYPES_PRIoFAST32
#define PRIoFAST64 _LIBC_IMPL_INTTYPES_PRIoFAST64
#define PRIoMAX _LIBC_IMPL_INTTYPES_PRIoMAX
#define PRIoPTR _LIBC_IMPL_INTTYPES_PRIoPTR
#define PRIu8 _LIBC_IMPL_INTTYPES_PRIu8
#define PRIu16 _LIBC_IMPL_INTTYPES_PRIu16
#define PRIu32 _LIBC_IMPL_INTTYPES_PRIu32
#define PRIu64 _LIBC_IMPL_INTTYPES_PRIu64
#define PRIuLEAST8 _LIBC_IMPL_INTTYPES_PRIuLEAST8
#define PRIuLEAST16 _LIBC_IMPL_INTTYPES_PRIuLEAST16
#define PRIuLEAST32 _LIBC_IMPL_INTTYPES_PRIuLEAST32
#define PRIuLEAST64 _LIBC_IMPL_INTTYPES_PRIuLEAST64
#define PRIuFAST8 _LIBC_IMPL_INTTYPES_PRIuFAST8
#define PRIuFAST16 _LIBC_IMPL_INTTYPES_PRIuFAST16
#define PRIuFAST32 _LIBC_IMPL_INTTYPES_PRIuFAST32
#define PRIuFAST64 _LIBC_IMPL_INTTYPES_PRIuFAST64
#define PRIuMAX _LIBC_IMPL_INTTYPES_PRIuMAX
#define PRIuPTR _LIBC_IMPL_INTTYPES_PRIuPTR
#define PRIx8 _LIBC_IMPL_INTTYPES_PRIx8
#define PRIx16 _LIBC_IMPL_INTTYPES_PRIx16
#define PRIx32 _LIBC_IMPL_INTTYPES_PRIx32
#define PRIx64 _LIBC_IMPL_INTTYPES_PRIx64
#define PRIxLEAST8 _LIBC_IMPL_INTTYPES_PRIxLEAST8
#define PRIxLEAST16 _LIBC_IMPL_INTTYPES_PRIxLEAST16
#define PRIxLEAST32 _LIBC_IMPL_INTTYPES_PRIxLEAST32
#define PRIxLEAST64 _LIBC_IMPL_INTTYPES_PRIxLEAST64
#define PRIxFAST8 _LIBC_IMPL_INTTYPES_PRIxFAST8
#define PRIxFAST16 _LIBC_IMPL_INTTYPES_PRIxFAST16
#define PRIxFAST32 _LIBC_IMPL_INTTYPES_PRIxFAST32
#define PRIxFAST64 _LIBC_IMPL_INTTYPES_PRIxFAST64
#define PRIxMAX _LIBC_IMPL_INTTYPES_PRIxMAX
#define PRIxPTR _LIBC_IMPL_INTTYPES_PRIxPTR
#define PRIX8 _LIBC_IMPL_INTTYPES_PRIX8
#define PRIX16 _LIBC_IMPL_INTTYPES_PRIX16
#define PRIX32 _LIBC_IMPL_INTTYPES_PRIX32
#define PRIX64 _LIBC_IMPL_INTTYPES_PRIX64
#define PRIXLEAST8 _LIBC_IMPL_INTTYPES_PRIXLEAST8
#define PRIXLEAST16 _LIBC_IMPL_INTTYPES_PRIXLEAST16
#define PRIXLEAST32 _LIBC_IMPL_INTTYPES_PRIXLEAST32
#define PRIXLEAST64 _LIBC_IMPL_INTTYPES_PRIXLEAST64
#define PRIXFAST8 _LIBC_IMPL_INTTYPES_PRIXFAST8
#define PRIXFAST16 _LIBC_IMPL_INTTYPES_PRIXFAST16
#define PRIXFAST32 _LIBC_IMPL_INTTYPES_PRIXFAST32
#define PRIXFAST64 _LIBC_IMPL_INTTYPES_PRIXFAST64
#define PRIXMAX _LIBC_IMPL_INTTYPES_PRIXMAX
#define PRIXPTR _LIBC_IMPL_INTTYPES_PRIXPTR
#define SCNd8 _LIBC_IMPL_INTTYPES_SCNd8
#define SCNd16 _LIBC_IMPL_INTTYPES_SCNd16
#define SCNd32 _LIBC_IMPL_INTTYPES_SCNd32
#define SCNd64 _LIBC_IMPL_INTTYPES_SCNd64
#define SCNdLEAST8 _LIBC_IMPL_INTTYPES_SCNdLEAST8
#define SCNdLEAST16 _LIBC_IMPL_INTTYPES_SCNdLEAST16
#define SCNdLEAST32 _LIBC_IMPL_INTTYPES_SCNdLEAST32
#define SCNdLEAST64 _LIBC_IMPL_INTTYPES_SCNdLEAST64
#define SCNdFAST8 _LIBC_IMPL_INTTYPES_SCNdFAST8
#define SCNdFAST16 _LIBC_IMPL_INTTYPES_SCNdFAST16
#define SCNdFAST32 _LIBC_IMPL_INTTYPES_SCNdFAST32
#define SCNdFAST64 _LIBC_IMPL_INTTYPES_SCNdFAST64
#define SCNdMAX _LIBC_IMPL_INTTYPES_SCNdMAX
#define SCNdPTR _LIBC_IMPL_INTTYPES_SCNdPTR
#define SCNi8 _LIBC_IMPL_INTTYPES_SCNi8
#define SCNi16 _LIBC_IMPL_INTTYPES_SCNi16
#define SCNi32 _LIBC_IMPL_INTTYPES_SCNi32
#define SCNi64 _LIBC_IMPL_INTTYPES_SCNi64
#define SCNiLEAST8 _LIBC_IMPL_INTTYPES_SCNiLEAST8
#define SCNiLEAST16 _LIBC_IMPL_INTTYPES_SCNiLEAST16
#define SCNiLEAST32 _LIBC_IMPL_INTTYPES_SCNiLEAST32
#define SCNiLEAST64 _LIBC_IMPL_INTTYPES_SCNiLEAST64
#define SCNiFAST8 _LIBC_IMPL_INTTYPES_SCNiFAST8
#define SCNiFAST16 _LIBC_IMPL_INTTYPES_SCNiFAST16
#define SCNiFAST32 _LIBC_IMPL_INTTYPES_SCNiFAST32
#define SCNiFAST64 _LIBC_IMPL_INTTYPES_SCNiFAST64
#define SCNiMAX _LIBC_IMPL_INTTYPES_SCNiMAX
#define SCNiPTR _LIBC_IMPL_INTTYPES_SCNiPTR
#define SCNo8 _LIBC_IMPL_INTTYPES_SCNo8
#define SCNo16 _LIBC_IMPL_INTTYPES_SCNo16
#define SCNo32 _LIBC_IMPL_INTTYPES_SCNo32
#define SCNo64 _LIBC_IMPL_INTTYPES_SCNo64
#define SCNoLEAST8 _LIBC_IMPL_INTTYPES_SCNoLEAST8
#define SCNoLEAST16 _LIBC_IMPL_INTTYPES_SCNoLEAST16
#define SCNoLEAST32 _LIBC_IMPL_INTTYPES_SCNoLEAST32
#define SCNoLEAST64 _LIBC_IMPL_INTTYPES_SCNoLEAST64
#define SCNoFAST8 _LIBC_IMPL_INTTYPES_SCNoFAST8
#define SCNoFAST16 _LIBC_IMPL_INTTYPES_SCNoFAST16
#define SCNoFAST32 _LIBC_IMPL_INTTYPES_SCNoFAST32
#define SCNoFAST64 _LIBC_IMPL_INTTYPES_SCNoFAST64
#define SCNoMAX _LIBC_IMPL_INTTYPES_SCNoMAX
#define SCNoPTR _LIBC_IMPL_INTTYPES_SCNoPTR
#define SCNu8 _LIBC_IMPL_INTTYPES_SCNu8
#define SCNu16 _LIBC_IMPL_INTTYPES_SCNu16
#define SCNu32 _LIBC_IMPL_INTTYPES_SCNu32
#define SCNu64 _LIBC_IMPL_INTTYPES_SCNu64
#define SCNuLEAST8 _LIBC_IMPL_INTTYPES_SCNuLEAST8
#define SCNuLEAST16 _LIBC_IMPL_INTTYPES_SCNuLEAST16
#define SCNuLEAST32 _LIBC_IMPL_INTTYPES_SCNuLEAST32
#define SCNuLEAST64 _LIBC_IMPL_INTTYPES_SCNuLEAST64
#define SCNuFAST8 _LIBC_IMPL_INTTYPES_SCNuFAST8
#define SCNuFAST16 _LIBC_IMPL_INTTYPES_SCNuFAST16
#define SCNuFAST32 _LIBC_IMPL_INTTYPES_SCNuFAST32
#define SCNuFAST64 _LIBC_IMPL_INTTYPES_SCNuFAST64
#define SCNuMAX _LIBC_IMPL_INTTYPES_SCNuMAX
#define SCNuPTR _LIBC_IMPL_INTTYPES_SCNuPTR
#define SCNx8 _LIBC_IMPL_INTTYPES_SCNx8
#define SCNx16 _LIBC_IMPL_INTTYPES_SCNx16
#define SCNx32 _LIBC_IMPL_INTTYPES_SCNx32
#define SCNx64 _LIBC_IMPL_INTTYPES_SCNx64
#define SCNxLEAST8 _LIBC_IMPL_INTTYPES_SCNxLEAST8
#define SCNxLEAST16 _LIBC_IMPL_INTTYPES_SCNxLEAST16
#define SCNxLEAST32 _LIBC_IMPL_INTTYPES_SCNxLEAST32
#define SCNxLEAST64 _LIBC_IMPL_INTTYPES_SCNxLEAST64
#define SCNxFAST8 _LIBC_IMPL_INTTYPES_SCNxFAST8
#define SCNxFAST16 _LIBC_IMPL_INTTYPES_SCNxFAST16
#define SCNxFAST32 _LIBC_IMPL_INTTYPES_SCNxFAST32
#define SCNxFAST64 _LIBC_IMPL_INTTYPES_SCNxFAST64
#define SCNxMAX _LIBC_IMPL_INTTYPES_SCNxMAX
#define SCNxPTR _LIBC_IMPL_INTTYPES_SCNxPTR

// (S7.8.2) Functions for greatest-width integer types
intmax_t imaxabs(intmax_t j);
imaxdiv_t imaxdiv(intmax_t numer, intmax_t denom);
intmax_t strtoimax(const char *restrict nptr, char **restrict endptr, int base);
uintmax_t strtoumax(const char *restrict nptr, char **restrict endptr, int base);
intmax_t wcstoimax(const _Libc_Impl_Stddef_wchar_t *restrict nptr, _Libc_Impl_Stddef_wchar_t **restrict endptr, int base);
uintmax_t wcstoumax(const _Libc_Impl_Stddef_wchar_t *restrict nptr, _Libc_Impl_Stddef_wchar_t **restrict endptr, int base);

#endif // __INTTYPES_H__
