/*
 * C header file for format conversion of integer types.
 *
 * Copyright (C) 2026 Ivan Janevski
 *
 * ivancc is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * ivancc is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * for more details.
 *
 * Under Section 7 of GPL version 3, you are granted additional
 * permissions described in the GCC Runtime Library Exception, version
 * 3.1, as published by the Free Software Foundation.
 *
 * You should have received a copy of the GNU General Public License and
 * a copy of the GCC Runtime Library Exception along with ivancc; see
 * the files LICENSE and COPYING.RUNTIME respectively.  If not, see
 * <https://www.gnu.org/licenses/>.
 */

#ifndef __INTTYPES_H__
#define __INTTYPES_H__

// Standard headers.
#include <stdint.h>

// The implementation.
#include <libc/impl/libc_inttypes.h>

// (S7.8) Format conversion of integer types
typedef __libc_impl_inttypes_imaxdiv_t imaxdiv_t;

// (S7.8.1) Macros for format specifiers
#define PRId8 __LIBC_IMPL_INTTYPES_PRId8
#define PRId16 __LIBC_IMPL_INTTYPES_PRId16
#define PRId32 __LIBC_IMPL_INTTYPES_PRId32
#define PRId64 __LIBC_IMPL_INTTYPES_PRId64
#define PRIdLEAST8 __LIBC_IMPL_INTTYPES_PRIdLEAST8
#define PRIdLEAST16 __LIBC_IMPL_INTTYPES_PRIdLEAST16
#define PRIdLEAST32 __LIBC_IMPL_INTTYPES_PRIdLEAST32
#define PRIdLEAST64 __LIBC_IMPL_INTTYPES_PRIdLEAST64
#define PRIdFAST8 __LIBC_IMPL_INTTYPES_PRIdFAST8
#define PRIdFAST16 __LIBC_IMPL_INTTYPES_PRIdFAST16
#define PRIdFAST32 __LIBC_IMPL_INTTYPES_PRIdFAST32
#define PRIdFAST64 __LIBC_IMPL_INTTYPES_PRIdFAST64
#define PRIdMAX __LIBC_IMPL_INTTYPES_PRIdMAX
#define PRIdPTR __LIBC_IMPL_INTTYPES_PRIdPTR
#define PRIi8 __LIBC_IMPL_INTTYPES_PRIi8
#define PRIi16 __LIBC_IMPL_INTTYPES_PRIi16
#define PRIi32 __LIBC_IMPL_INTTYPES_PRIi32
#define PRIi64 __LIBC_IMPL_INTTYPES_PRIi64
#define PRIiLEAST8 __LIBC_IMPL_INTTYPES_PRIiLEAST8
#define PRIiLEAST16 __LIBC_IMPL_INTTYPES_PRIiLEAST16
#define PRIiLEAST32 __LIBC_IMPL_INTTYPES_PRIiLEAST32
#define PRIiLEAST64 __LIBC_IMPL_INTTYPES_PRIiLEAST64
#define PRIiFAST8 __LIBC_IMPL_INTTYPES_PRIiFAST8
#define PRIiFAST16 __LIBC_IMPL_INTTYPES_PRIiFAST16
#define PRIiFAST32 __LIBC_IMPL_INTTYPES_PRIiFAST32
#define PRIiFAST64 __LIBC_IMPL_INTTYPES_PRIiFAST64
#define PRIiMAX __LIBC_IMPL_INTTYPES_PRIiMAX
#define PRIiPTR __LIBC_IMPL_INTTYPES_PRIiPTR
#define PRIo8 __LIBC_IMPL_INTTYPES_PRIo8
#define PRIo16 __LIBC_IMPL_INTTYPES_PRIo16
#define PRIo32 __LIBC_IMPL_INTTYPES_PRIo32
#define PRIo64 __LIBC_IMPL_INTTYPES_PRIo64
#define PRIoLEAST8 __LIBC_IMPL_INTTYPES_PRIoLEAST8
#define PRIoLEAST16 __LIBC_IMPL_INTTYPES_PRIoLEAST16
#define PRIoLEAST32 __LIBC_IMPL_INTTYPES_PRIoLEAST32
#define PRIoLEAST64 __LIBC_IMPL_INTTYPES_PRIoLEAST64
#define PRIoFAST8 __LIBC_IMPL_INTTYPES_PRIoFAST8
#define PRIoFAST16 __LIBC_IMPL_INTTYPES_PRIoFAST16
#define PRIoFAST32 __LIBC_IMPL_INTTYPES_PRIoFAST32
#define PRIoFAST64 __LIBC_IMPL_INTTYPES_PRIoFAST64
#define PRIoMAX __LIBC_IMPL_INTTYPES_PRIoMAX
#define PRIoPTR __LIBC_IMPL_INTTYPES_PRIoPTR
#define PRIu8 __LIBC_IMPL_INTTYPES_PRIu8
#define PRIu16 __LIBC_IMPL_INTTYPES_PRIu16
#define PRIu32 __LIBC_IMPL_INTTYPES_PRIu32
#define PRIu64 __LIBC_IMPL_INTTYPES_PRIu64
#define PRIuLEAST8 __LIBC_IMPL_INTTYPES_PRIuLEAST8
#define PRIuLEAST16 __LIBC_IMPL_INTTYPES_PRIuLEAST16
#define PRIuLEAST32 __LIBC_IMPL_INTTYPES_PRIuLEAST32
#define PRIuLEAST64 __LIBC_IMPL_INTTYPES_PRIuLEAST64
#define PRIuFAST8 __LIBC_IMPL_INTTYPES_PRIuFAST8
#define PRIuFAST16 __LIBC_IMPL_INTTYPES_PRIuFAST16
#define PRIuFAST32 __LIBC_IMPL_INTTYPES_PRIuFAST32
#define PRIuFAST64 __LIBC_IMPL_INTTYPES_PRIuFAST64
#define PRIuMAX __LIBC_IMPL_INTTYPES_PRIuMAX
#define PRIuPTR __LIBC_IMPL_INTTYPES_PRIuPTR
#define PRIx8 __LIBC_IMPL_INTTYPES_PRIx8
#define PRIx16 __LIBC_IMPL_INTTYPES_PRIx16
#define PRIx32 __LIBC_IMPL_INTTYPES_PRIx32
#define PRIx64 __LIBC_IMPL_INTTYPES_PRIx64
#define PRIxLEAST8 __LIBC_IMPL_INTTYPES_PRIxLEAST8
#define PRIxLEAST16 __LIBC_IMPL_INTTYPES_PRIxLEAST16
#define PRIxLEAST32 __LIBC_IMPL_INTTYPES_PRIxLEAST32
#define PRIxLEAST64 __LIBC_IMPL_INTTYPES_PRIxLEAST64
#define PRIxFAST8 __LIBC_IMPL_INTTYPES_PRIxFAST8
#define PRIxFAST16 __LIBC_IMPL_INTTYPES_PRIxFAST16
#define PRIxFAST32 __LIBC_IMPL_INTTYPES_PRIxFAST32
#define PRIxFAST64 __LIBC_IMPL_INTTYPES_PRIxFAST64
#define PRIxMAX __LIBC_IMPL_INTTYPES_PRIxMAX
#define PRIxPTR __LIBC_IMPL_INTTYPES_PRIxPTR
#define PRIX8 __LIBC_IMPL_INTTYPES_PRIX8
#define PRIX16 __LIBC_IMPL_INTTYPES_PRIX16
#define PRIX32 __LIBC_IMPL_INTTYPES_PRIX32
#define PRIX64 __LIBC_IMPL_INTTYPES_PRIX64
#define PRIXLEAST8 __LIBC_IMPL_INTTYPES_PRIXLEAST8
#define PRIXLEAST16 __LIBC_IMPL_INTTYPES_PRIXLEAST16
#define PRIXLEAST32 __LIBC_IMPL_INTTYPES_PRIXLEAST32
#define PRIXLEAST64 __LIBC_IMPL_INTTYPES_PRIXLEAST64
#define PRIXFAST8 __LIBC_IMPL_INTTYPES_PRIXFAST8
#define PRIXFAST16 __LIBC_IMPL_INTTYPES_PRIXFAST16
#define PRIXFAST32 __LIBC_IMPL_INTTYPES_PRIXFAST32
#define PRIXFAST64 __LIBC_IMPL_INTTYPES_PRIXFAST64
#define PRIXMAX __LIBC_IMPL_INTTYPES_PRIXMAX
#define PRIXPTR __LIBC_IMPL_INTTYPES_PRIXPTR
#define SCNd8 __LIBC_IMPL_INTTYPES_SCNd8
#define SCNd16 __LIBC_IMPL_INTTYPES_SCNd16
#define SCNd32 __LIBC_IMPL_INTTYPES_SCNd32
#define SCNd64 __LIBC_IMPL_INTTYPES_SCNd64
#define SCNdLEAST8 __LIBC_IMPL_INTTYPES_SCNdLEAST8
#define SCNdLEAST16 __LIBC_IMPL_INTTYPES_SCNdLEAST16
#define SCNdLEAST32 __LIBC_IMPL_INTTYPES_SCNdLEAST32
#define SCNdLEAST64 __LIBC_IMPL_INTTYPES_SCNdLEAST64
#define SCNdFAST8 __LIBC_IMPL_INTTYPES_SCNdFAST8
#define SCNdFAST16 __LIBC_IMPL_INTTYPES_SCNdFAST16
#define SCNdFAST32 __LIBC_IMPL_INTTYPES_SCNdFAST32
#define SCNdFAST64 __LIBC_IMPL_INTTYPES_SCNdFAST64
#define SCNdMAX __LIBC_IMPL_INTTYPES_SCNdMAX
#define SCNdPTR __LIBC_IMPL_INTTYPES_SCNdPTR
#define SCNi8 __LIBC_IMPL_INTTYPES_SCNi8
#define SCNi16 __LIBC_IMPL_INTTYPES_SCNi16
#define SCNi32 __LIBC_IMPL_INTTYPES_SCNi32
#define SCNi64 __LIBC_IMPL_INTTYPES_SCNi64
#define SCNiLEAST8 __LIBC_IMPL_INTTYPES_SCNiLEAST8
#define SCNiLEAST16 __LIBC_IMPL_INTTYPES_SCNiLEAST16
#define SCNiLEAST32 __LIBC_IMPL_INTTYPES_SCNiLEAST32
#define SCNiLEAST64 __LIBC_IMPL_INTTYPES_SCNiLEAST64
#define SCNiFAST8 __LIBC_IMPL_INTTYPES_SCNiFAST8
#define SCNiFAST16 __LIBC_IMPL_INTTYPES_SCNiFAST16
#define SCNiFAST32 __LIBC_IMPL_INTTYPES_SCNiFAST32
#define SCNiFAST64 __LIBC_IMPL_INTTYPES_SCNiFAST64
#define SCNiMAX __LIBC_IMPL_INTTYPES_SCNiMAX
#define SCNiPTR __LIBC_IMPL_INTTYPES_SCNiPTR
#define SCNo8 __LIBC_IMPL_INTTYPES_SCNo8
#define SCNo16 __LIBC_IMPL_INTTYPES_SCNo16
#define SCNo32 __LIBC_IMPL_INTTYPES_SCNo32
#define SCNo64 __LIBC_IMPL_INTTYPES_SCNo64
#define SCNoLEAST8 __LIBC_IMPL_INTTYPES_SCNoLEAST8
#define SCNoLEAST16 __LIBC_IMPL_INTTYPES_SCNoLEAST16
#define SCNoLEAST32 __LIBC_IMPL_INTTYPES_SCNoLEAST32
#define SCNoLEAST64 __LIBC_IMPL_INTTYPES_SCNoLEAST64
#define SCNoFAST8 __LIBC_IMPL_INTTYPES_SCNoFAST8
#define SCNoFAST16 __LIBC_IMPL_INTTYPES_SCNoFAST16
#define SCNoFAST32 __LIBC_IMPL_INTTYPES_SCNoFAST32
#define SCNoFAST64 __LIBC_IMPL_INTTYPES_SCNoFAST64
#define SCNoMAX __LIBC_IMPL_INTTYPES_SCNoMAX
#define SCNoPTR __LIBC_IMPL_INTTYPES_SCNoPTR
#define SCNu8 __LIBC_IMPL_INTTYPES_SCNu8
#define SCNu16 __LIBC_IMPL_INTTYPES_SCNu16
#define SCNu32 __LIBC_IMPL_INTTYPES_SCNu32
#define SCNu64 __LIBC_IMPL_INTTYPES_SCNu64
#define SCNuLEAST8 __LIBC_IMPL_INTTYPES_SCNuLEAST8
#define SCNuLEAST16 __LIBC_IMPL_INTTYPES_SCNuLEAST16
#define SCNuLEAST32 __LIBC_IMPL_INTTYPES_SCNuLEAST32
#define SCNuLEAST64 __LIBC_IMPL_INTTYPES_SCNuLEAST64
#define SCNuFAST8 __LIBC_IMPL_INTTYPES_SCNuFAST8
#define SCNuFAST16 __LIBC_IMPL_INTTYPES_SCNuFAST16
#define SCNuFAST32 __LIBC_IMPL_INTTYPES_SCNuFAST32
#define SCNuFAST64 __LIBC_IMPL_INTTYPES_SCNuFAST64
#define SCNuMAX __LIBC_IMPL_INTTYPES_SCNuMAX
#define SCNuPTR __LIBC_IMPL_INTTYPES_SCNuPTR
#define SCNx8 __LIBC_IMPL_INTTYPES_SCNx8
#define SCNx16 __LIBC_IMPL_INTTYPES_SCNx16
#define SCNx32 __LIBC_IMPL_INTTYPES_SCNx32
#define SCNx64 __LIBC_IMPL_INTTYPES_SCNx64
#define SCNxLEAST8 __LIBC_IMPL_INTTYPES_SCNxLEAST8
#define SCNxLEAST16 __LIBC_IMPL_INTTYPES_SCNxLEAST16
#define SCNxLEAST32 __LIBC_IMPL_INTTYPES_SCNxLEAST32
#define SCNxLEAST64 __LIBC_IMPL_INTTYPES_SCNxLEAST64
#define SCNxFAST8 __LIBC_IMPL_INTTYPES_SCNxFAST8
#define SCNxFAST16 __LIBC_IMPL_INTTYPES_SCNxFAST16
#define SCNxFAST32 __LIBC_IMPL_INTTYPES_SCNxFAST32
#define SCNxFAST64 __LIBC_IMPL_INTTYPES_SCNxFAST64
#define SCNxMAX __LIBC_IMPL_INTTYPES_SCNxMAX
#define SCNxPTR __LIBC_IMPL_INTTYPES_SCNxPTR

// (S7.8.2) Functions for greatest-width integer types
intmax_t imaxabs(intmax_t j);
imaxdiv_t imaxdiv(intmax_t numer, intmax_t denom);
intmax_t strtoimax(const char *restrict nptr, char **restrict endptr, int base);
uintmax_t strtoumax(const char *restrict nptr, char **restrict endptr, int base);
intmax_t wcstoimax(const __libc_impl_stddef_wchar_t *restrict nptr, __libc_impl_stddef_wchar_t **restrict endptr, int base);
uintmax_t wcstoumax(const __libc_impl_stddef_wchar_t *restrict nptr, __libc_impl_stddef_wchar_t **restrict endptr, int base);

#endif // __INTTYPES_H__
